<a href="https://colab.research.google.com/github/aman2008-CODER/Open_Sourcery-2.0/blob/main/phython_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# str='aman'                        # is used to comment
# print("my name is",str)

# n=int(input("enter the age"))
# print("the age is:",n)

# weight=70.86
# print(type(weight))  # this show what is the type of weight ex: int,char , float ,str, list,tuple , dict etc

# if(n>=18):
#  print("the person is eligible to vote")
# elif(n<=18):
#  print("the person is not eligible to vote")
# else:
#  print("wrong output")


In [ ]:
# for i in range(5):            ## for(i=0;i=5;i++) this is done in c language
#   for j in range(5):
#     print("*", end="")
#   print()

# for i in range(0,5):    # range(start,stop,skip)
#    for j in range(i,5):
#     print("*", end="")
#    print()

# for i in range(0,5):
#   for j in range(i,3):
#     print("*", end="")
#   print()

In [ ]:
# wap to reverse a number
n=int(input("enter the value "))
a=n
r=0
while(n>0):
  ld=n%10
  r=r*10+ld
  n=n//10
print("the reverse of a number is",r)

# Removed the line 'r=b' as 'b' was undefined and 'r' already holds the reversed number.
# Changed 'if(a==b)' to 'if(a==r)' to compare the original number with its reverse.
if(a==r):
  print("the number is palindrome")
else:
  print("the number is not palindrome")

enter the value 555
the reverse of a number is 555
the number is palindrome


In [ ]:
## NUMPY
# CREATING NUMPY ARRAYS

# USING ARRAY METHOD  ##array()

import numpy as np ## to create a numpy array you have to pass a list to the array() method of the numpy module
num_list =[10,20,30,40,50]
num_array=np.array(num_list)

## CREATING TWO DIMENSIONAL ARRAY USING array() method , in this we have to pass list of list in array
row1=[10,11,12,13]
row2=[40,45,50,55]
row3=[45,54,65,78]

num_2D = np.array([row1,row2,row3])
num_2D.shape ## THIS COMMAND IS USED TO TELL THE SHAPE OF MATRIX EX-- /// ROWS AND COLUMMS /// OUTPUT IS (3,4) MEANS 3 ROWS AND 4 COLUMMS



##////// USING ARANGE METHOD ////////

## WE CAN USE arange() method to CREATE AN ARRAY : IN THIS WE HAVE TO PASS STARTING AND ENDING INTEGER SAME AS IN RANGE(0,3)LAST 3 IS NOT INCLUDE
## IN THIS SIMILAR IN arange(5,11) output will [5,6,7,8,9,10] in form of aaray
num_arr=np.arange(5,11)
print(num_arr)## [5,6,7,8,9,10]

num_arr=np.arange(5,11,2)
print(num_arr) ## output [5,7,9]



## USING ONES METHOD

## THE ones() method canbe used to create a Numpy array of all ones in this array consist of only ones
ones_array=np.ones(6)
print(ones_array) ## output [1. 1. 1. 1. 1. 1.]

## WE CAN CREATE 2D ARRAT\Y USING ONES METHOD BY PASSING ROWS AND COULMN
ONES_ARRAY=np.ones((6,4))
print(ONES_ARRAY)
## OUTPUT
#  [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]


## USING ZEROS() METHOD SAME AS ONES() METHOD

ZERO_ARRAY=np.zeros(6)
print(ZERO_ARRAY)


## USING eye() method

# IS USED TO PRINT IDENTITY MATRIX
EYES_ARRAY=np.eye(5)
print(EYES_ARRAY)
## OUTPUT
# [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 1.]]



## USING RANDOM METHOD (THE MOST IMPORTANT METHOD USED IN MACHINE LEARNING PROGRAM)
## random.rand() function from the Numpy module can be useed to create a numpy aray with uniform distribution
#basically it give random value to array
uniform_random=np.random.rand(4,5)
print(uniform_random)
#OUTPUT (RANDOM VALUE IS INSERTED IN THE ARRAY ///// BUT VALUE IS BETWEEN 0 AND 1)
# [[0.94497894 0.31484579 0.51443073 0.80364295 0.01974656]
#  [0.23734969 0.50321987 0.57741867 0.54740398 0.36908572]
#  [0.1235348  0.97245762 0.54810991 0.45737511 0.86797932]
#  [0.78175629 0.05220443 0.78312635 0.90969241 0.45805773]]

## random.randn()

normal_random=np.random.randn(4, 5)
print(uniform_random)
## these two random.rand() or randn() give output in float
#OUTPUT SAME AS ABOVE
# [[0.94497894 0.31484579 0.51443073 0.80364295 0.01974656]
#  [0.23734969 0.50321987 0.57741867 0.54740398 0.36908572]
#  [0.1235348  0.97245762 0.54810991 0.45737511 0.86797932]
#  [0.78175629 0.05220443 0.78312635 0.90969241 0.45805773]]

## random.randint()

integer_random=np.random.randint(10,50,5) ## the first parameter specify the lower bound and second parameter specify upper bound whereas
# last parameter specify that how many number will be generated in array here (10 is lower bound , 50 is upper bound , 5 is number of element in array
print(integer_random)

# OUTPUT
# [49 44 23 36 25] RANDOM VALUE IS GENERATED IN THE ARRAY

# RESHAPING NUMPY Array

## reshape()
#IT IS USED TO RESHAPE THE SIZE OF ARRAY OR CHANGING ROWS AND COLUMN BUT THERE IS ONE CONDITION THAT:- (// THE PRODUCT OF THE ROWS AND COLUMNS IN
# THE RESHAPED ARRAY MUST BE EQUAL TO THE PRODUCT OF ROWS AND COLUMNS IN THE ORIGINAL ARRAY// )
uniform_random=np.random.rand(4,6)
uniform_random=uniform_random.reshape(3,8)
print(uniform_random)

## OUTPUT
# [[0.25635369 0.38172284 0.50508566 0.95137695 0.95998062 0.89109068
#   0.61690323 0.11129364]
#  [0.7154226  0.77711284 0.66156591 0.31091393 0.25379834 0.73579955
#   0.09952318 0.22465591]
#  [0.86090354 0.43306051 0.99797492 0.28423262 0.87164791 0.64810944
#   0.43259868 0.50982155]]
# IN THIS 3 ROW AND 8 COLUMNS OF RANDOM VALUES

## ARRAY INDEXING AND SLICING

s=np.arange(1,11)
print(s)
## OUTPUT [ 1  2  3  4  5  6  7  8  9 10]
print(s[2])         # HERE [2] IS INDEX OF THE ARRAY INDEXING START FROM 0
## output is 3
print(s[1:9])
## in this it will print the value of element at that index from 1 to 8 not 9 because 9 is not icluded in slicing or idexing here [1:9] are index
#OUTPUT is [2,3,4,5,6,7,8,9]

print(s[:5]) # IN THIS ALL THE ELEMENTS FROM THE FIRST INDEX TO THE UPPER BOUND INDEX ARE RETURNED
print(s[5:]) # IN THIS ALL THE ELEMENTS FROM THE LOWER BOUND INDEX T0 THE LAST INDEX WILL PRINT OR RETURNED
## OUTPUT
# [1 2 3 4 5]
# [ 6  7  8  9 10]

## INDEXING OR SLICIND CAN BE DONE IN 2D ARRAY

ROW1 = [10,12,13]
ROW2 = [45,32,16]
ROW3 = [43,32,16]

NUM_2D = np.array([ROW1,ROW2,ROW3])
print(NUM_2D)
#OUTPUT
# [[10 12 13]
#  [45 32 16]
#  [43 32 16]]

# print(NUM_2D[:2,:])  ## [:2,:] IN THIS [ROW INDEX ,COLUMN INDEX]
#OUTPUT
# [[10 12 13]
#  [45 32 16]]

print(NUM_2D[:2,:2])  ##[:2,:2] IN THIS [ROW INDEX IS 2 IT WILL TAKE ROWS AT 0 AND INDEX  ,COLUMN INDEX IS ALSO 2 IT WILL TAKE COLUMN AT 0 AND 1 INDEX]
#OUTPUT
# [[10 12]
#  [45 32]]


## USING NUMPY FOR ARTHIMETIC OPERATIONS
# Finding sqrt()
nums=[10,20,30,40]
np_sqrt=np.sqrt(nums)
print(np_sqrt)
#OUTPUT
#[3.16227766 4.47213595 5.47722558 6.32455532]

## np.log(), np.exp(), np.sin(),np.cos(), etc same as above

## finding matrix dot product
# To find matrix dot product , you can use dot() function to find the dot product,the number of column of first matrix must match the number of rows in second matrix
a=np.random.randn(4,5)
b=np.random.randn(5,4)
z=np.dot(a,b)
print(z)
##OUTPUT
# [[ 1.58967536 -0.02425117 -0.36100196 -0.50080681]
#  [-1.294275   -0.15584725  0.78333248  2.55764477]
#  [ 2.51568377  0.4708771   4.63829588 -1.74429317]
#  [-1.47927415 -0.78620596 -2.26361712 -0.21630186]]

## ELEMENT WISE MULTIPICATION IN THE MATRIX
row1=[10,12,13]
row2=[45,32,12]
row3=[45,32,16]

nums_2d=np.array([row1,row2,row3])
multiply=np.multiply(nums_2d,nums_2d)
print(multiply)
#OUTPUT
# [[ 100  144  169]
#  [2025 1024  144]
#  [2025 1024  256]]


## FINDING INVERSE OF A MATRIX BY USING linalg.inv()
row1=[10,12,13]
row2=[45,32,12]
row3=[45,32,16]

nums_2d=np.array([row1,row2,row3])
inverse= np.linalg.inv( nums_2d)
print(inverse)
##OUTPUT
# [[-0.14545455 -0.25454545  0.30909091]
#  [ 0.20454545  0.48295455 -0.52840909]
#  [ 0.         -0.25        0.25      ]]


##FINDING MATRIX DETERMINANT USING linalg.det()
row1=[10,12,13]
row2=[45,32,12]
row3=[45,32,16]

nums_2d=np.array([row1,row2,row3])
determinant=np.linalg.det(nums_2d)
print(determinant)
## OUTPUT
#-879.9999999999998


## FINDING TRACE OF A MATRIX
#TRACE OF A MATRIX REFER TO THE SUM OF ALL THE ELEMENTS ALONG THE DIAGONAL OF A MATRIX
row1=[10,12,13]
row2=[45,32,12]
row3=[45,32,16]

nums_2d=np.array([row1,row2,row3])
TRACE =np.trace(nums_2d)
print(TRACE)
##OUTPUT IS 58


